#pragma config(Motor,  port4,           elevatorLeft,  tmotorNormal, openLoop)
#pragma config(Motor,  port5,           elevatorLeftB, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port6,           leftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  port7,           rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port8,           elevatorRightB, tmotorNormal, openLoop)
#pragma config(Motor,  port9,           elevatorRight, tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)


#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

int threshold = 12.7;

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................

	  //UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.

		if(vexRT[Btn6D] == 1)
			{
				motor[elevatorLeft] = 127;
				motor[elevatorLeftB] = 127;
		}
		else
			{
						motor[elevatorLeft] = 0;
						motor[elevatorLeftB] = 0;
			}

		if(vexRT[Btn6U] == 1)
			{
				motor[elevatorRight] = -127;
				motor[elevatorRightB] = -127;
		}
		else
			{
						motor[elevatorRight] = 0;
						motor[elevatorRightB] = 0;
		}

		// Main wheels
	if (abs(vexRT[Ch3]) > threshold) // If the left joystick is greater than or less than the threshold:
	{
		motor[leftMotor] = (vexRT[Ch3]); // Left Joystick Y value / 2.
	}
	if (abs(vexRT[Ch3]) < threshold) // If the left joystick is within the threshold:
	{
		motor[leftMotor] = 0; // Stop the left motor (cancel noise)
	}
		if (abs(vexRT[Ch2]) > threshold) // If the left joystick is greater than or less than the threshold:
	{
		motor[rightMotor] = (vexRT[Ch2]); // Left Joystick Y value / 2.
	}
	if (abs(vexRT[Ch2]) < threshold) // If the left joystick is within the threshold:
	{
		motor[rightMotor] = 0; // Stop the left motor (cancel noise)
	}

	}
}
